disabled_rules:
  - trailing_comma
  - identifier_name
  - void_return
  - operator_whitespace
  - nesting
  - cyclomatic_complexity
  - opening_brace
  - todo
  - function_parameter_count
  - line_length
  - function_body_length
  - file_length

included:
  - Sources
  - Tests

excluded:
  - Tests/Fixtures
