version: '3.7'

services:

  carton:
    image: gchr.io/swiftwasm/swiftwasm-action:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carton
    command:
      - /bin/bash
      - -c
      - |
        cd /carton
        swift test -c release --enable-test-discovery
    volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/carton
