name: Release

on:
  release:
    types:
      - created

jobs:
  docker:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/swiftwasm/carton:${{ github.event.release.tag_name }}
            ghcr.io/swiftwasm/carton:latest

  formula:
    name: Update Homebrew formula
    runs-on: ubuntu-20.04
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: swiftwasm/carton
          tap: swiftwasm/homebrew-tap
          formula: carton.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
