name: Release

on:
  release:
    types:
      - created

jobs:
  docker:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/swiftwasm/carton:${{ github.event.release.tag_name }}
            ghcr.io/swiftwasm/carton:latest

  formula:
    name: Update Homebrew formula
    runs-on: ubuntu-20.04
    steps:
      - name: Update the Homebrew formula with latest release
        uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: swiftwasm/carton
          tap: swiftwasm/homebrew-tap
          formula: carton.rb
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}

  bottle:
    name: Build and distribute Homebrew bottle for macOS Catalina
    runs-on: macos-10.15
    needs: [formula]
    steps:
      - name: Build a bottle using Homebrew
        run: |
          brew install --build-bottle --verbose swiftwasm/tap/carton
          brew bottle swiftwasm/tap/carton
          mv ./carton--${{ github.event.release.tag_name }}.catalina.bottle*.tar.gz \
            ./carton--${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
      - name: Upload the bottle to the GitHub release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./carton--${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_name: carton-${{ github.event.release.tag_name }}.catalina.bottle.tar.gz
          asset_content_type: application/gzip

  update_formula_bottle:
    name: Update the Homebrew formula again with bottle
    runs-on: ubuntu-20.04
    needs: [bottle]
    steps:
      - uses: NSHipster/update-homebrew-formula-action@main
        with:
          repository: swiftwasm/carton
          tap: swiftwasm/homebrew-tap
          formula: carton.rb
          message: |
            Add bottle for carton ${{ github.event.release.tag_name }}
            on macOS Catalina
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.PAT }}
