name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swift-test-macos:
    name: Build and test on macOS with Swift ${{ matrix.swift_version }}
    timeout-minutes: 40
    runs-on: macos-13
    strategy:
      matrix:
        include:
          - os: macos-13 # TODO: macos-14 runner expected in October-December 2023
            swift_version: "5.9"
            xcode: /Applications/Xcode_15.0.app/Contents/Developer

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select --switch ${{ matrix.xcode }}

      - name: Check Swift version
        run: swift --version

      - name: Install dependencies for macOS
        run: brew bundle

      - name: Build the project
        run: swift build --build-tests
      
      - name: Run tests
        run: swift test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  swift-test-linux:
    name: Build and test on Linux with Swift ${{ matrix.swift.version }}
    timeout-minutes: 40
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - swift:
              dir: "swift-5.9-release/ubuntu2204"
              version: "swift-5.9-RELEASE"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install Swift toolchain
        uses: ./.github/actions/install-swift
        with:
          swift-dir: ${{ matrix.swift.dir }}
          swift-version: ${{ matrix.swift.version }}

      - name: Check Swift version
        run: swift --version

      - name: Install dependent packages for WebAssembly
        run: >
          sudo apt-get update && sudo apt-get install -y
          wabt binaryen

      - name: Install WebAssembly runtime
        uses: bytecodealliance/actions/wasmtime/setup@v1

      - name: Build the project
        run: swift build --build-tests

      - name: Run tests
        run: swift test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
