name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  swift-test:
    strategy:
      matrix:
        include:
          - os: macos-10.15
            swift_version: 5.2
            xcode: /Applications/Xcode_11.7.app/Contents/Developer
          - os: macos-10.15
            swift_version: 5.3
            xcode: /Applications/Xcode_12.app/Contents/Developer
          # - os: macos-11.0
          #   swift_version: 5.2
          #   xcode: /Applications/Xcode_11.7.app/Contents/Developer
          # - os: macos-11.0
          #   swift_version: 5.3
          #   xcode: /Applications/Xcode_12.2.app/Contents/Developer
          - os: ubuntu-18.04
            swift_version: 5.4
          - os: ubuntu-20.04
            swift_version: 5.4
    name: Build on ${{ matrix.os }} with Swift ${{ matrix.swift_version }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode version
        run: sudo xcode-select --switch ${{ matrix.xcode }}
        if: startsWith(matrix.os, 'macos')

      - name: Cleanup pre-installed SwiftLint
        run: rm -f '/usr/local/bin/swiftlint'

      - name: Install dependencies for macOS
        run: brew bundle
        if: startsWith(matrix.os, 'macos')

      - name: Install dependencies for Ubuntu
        run: |
          sudo ./install_ubuntu_deps.sh
          curl https://get.wasmer.io -sSfL | sh
        if: startsWith(matrix.os, 'ubuntu')

      - name: Build the project
        run: swift build

      - name: Build and install JavaScript and sanitizer resources
        run: |
          set -ex
          npm install
          swift run carton-release hash-archive
          mkdir -p $HOME/.carton
          cp -r static $HOME/.carton/static
          ls -R  $HOME/.carton/static

      - name: Run Tests
        run: |
          set -ex
          if [ -e /home/runner/.wasmer/wasmer.sh ]; then
            source /home/runner/.wasmer/wasmer.sh
          fi
          swift test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build a Docker image on Ubuntu 20.04
        run: docker build . -t gchr.io/swiftwasm/swiftwasm-action:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
